package com.kunj.SmartHomeEnergyManagementSystem.Service;

import com.kunj.SmartHomeEnergyManagementSystem.Repository.AuditLogRepository;
import com.kunj.SmartHomeEnergyManagementSystem.Repository.UserRepository;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.LinkedHashMap;
import java.util.Map;

@Service
@Slf4j
public class ReportService
{
    @Autowired
    private UserRepository userRepository;

    @Autowired
    private AuditLogRepository auditLogRepository;

    @Autowired
    private AuditLogService auditLogService;


     // Build a system-wide summary report as a structured map.
     // The AdminController serialises this to JSON and also offers CSV download.
    public ReportData generateSystemReport(Long requestedByUserId) {

        LocalDateTime startOfToday  = LocalDate.now().atStartOfDay();
        LocalDateTime startOfMonth  = LocalDate.now().withDayOfMonth(1).atStartOfDay();

        // ── Counts ────────────────────────────────────────────────────────────
        long totalUsers      = userRepository.count();
        long enabledUsers    = userRepository.findAll().stream()
                .filter(u -> Boolean.TRUE.equals(u.getEnabled())).count();
        long twoFaUsers      = userRepository.findAll().stream()
                .filter(u -> Boolean.TRUE.equals(u.getTwoFactorEnabled())).count();

        AuditLogService.LogSummaryDTO logSummary = auditLogService.getSummary();

        // ── Assemble report ───────────────────────────────────────────────────
        Map<String, Object> meta = new LinkedHashMap<>();
        meta.put("generatedAt",    LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME));
        meta.put("generatedBy",    requestedByUserId != null ? requestedByUserId.toString() : "system");
        meta.put("reportPeriod",   "All-time + today (" + LocalDate.now() + ")");

        Map<String, Object> userStats = new LinkedHashMap<>();
        userStats.put("totalUsers",       totalUsers);
        userStats.put("enabledUsers",     enabledUsers);
        userStats.put("disabledUsers",    totalUsers - enabledUsers);
        userStats.put("twoFaEnabledUsers", twoFaUsers);

        Map<String, Object> securityStats = new LinkedHashMap<>();
        securityStats.put("totalAuditLogs",  logSummary.total());
        securityStats.put("infoEvents",      logSummary.infoCount());
        securityStats.put("warnEvents",      logSummary.warnCount());
        securityStats.put("errorEvents",     logSummary.errorCount());
        securityStats.put("todayEvents",     logSummary.todayCount());

        // Audit this report generation
        auditLogService.logInfo(requestedByUserId, "REPORT_GENERATED",
                "System report generated by user " + requestedByUserId);

        return new ReportData(meta, userStats, securityStats);
    }


     // Convert a ReportData to CSV text (suitable for file download).
    public String toCsv(ReportData report) {
        StringBuilder sb = new StringBuilder();
        sb.append("SMART HOME ENERGY MANAGEMENT - SYSTEM REPORT\n\n");

        sb.append("=== META ===\n");
        report.meta().forEach((k, v) -> sb.append(k).append(",").append(v).append("\n"));

        sb.append("\n=== USER STATISTICS ===\n");
        report.userStats().forEach((k, v) -> sb.append(k).append(",").append(v).append("\n"));

        sb.append("\n=== SECURITY STATISTICS ===\n");
        report.securityStats().forEach((k, v) -> sb.append(k).append(",").append(v).append("\n"));

        return sb.toString();
    }

    public record ReportData(
            Map<String, Object> meta,
            Map<String, Object> userStats,
            Map<String, Object> securityStats
    ) {}
}
