spring.application.name=SmartHomeEnergyManagementSystem

server.port=9091

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3300/energy_management_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=create-drop

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

#  IoT Simulation Settings
# Enable/disable automatic IoT data generation
iot.simulation.enabled=true

# Interval for generating IoT readings (milliseconds)
# Default: 30000 (30 seconds)
iot.simulation.interval=30000

# Data retention period (days)
iot.simulation.retention-days=30

# ===== Scheduler Settings =====
# Enable task scheduling
spring.task.scheduling.enabled=true

# Thread pool size for scheduled tasks
spring.task.scheduling.pool.size=5

# Maximum data points for real-time charts
realtime.chart.max-points=50

# Real-time data refresh interval (seconds)
realtime.refresh-interval=30

# Alert threshold - power usage overrated capacity (%)
realtime.alert.threshold-percent=110

# Critical alert threshold (%)
realtime.alert.critical-threshold-percent=120

